---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ist1
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.19.3
    app: ist1
    istio: ist1
    app.kubernetes.io/version: "1.19.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ist1
  annotations:
    {}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ist1
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.19.3
    app: ist1
    istio: ist1
    app.kubernetes.io/version: "1.19.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ist1
  annotations:
    {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ist1
subjects:
- kind: ServiceAccount
  name: ist1
