---
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ist1
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.19.3
    app: ist1
    istio: ist1
    app.kubernetes.io/version: "1.19.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ist1
  annotations:
    {}
spec:
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ist1
    istio: ist1
