---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ist1
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.19.3
    app: ist1
    istio: ist1
    app.kubernetes.io/version: "1.19.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ist1
