kind: Deployment
apiVersion: apps/v1
metadata:
  name: productpage-v1
  namespace: ns-bookinfo
  labels:
    app: productpage
    version: v1
    virtual-kubelet.io/burst-to-cci: enforce
  annotations:
    deployment.kubernetes.io/revision: '3'
    description: ''
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"productpage","version":"v1"},"name":"productpage-v1","namespace":"ns-bookinfo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"productpage","version":"v1"}},"template":{"metadata":{"labels":{"app":"productpage","version":"v1"}},"spec":{"containers":[{"image":"swr.cn-north-4.myhuaweicloud.com/hfbbg4/examples-bookinfo-productpage-v1:1.17.0","imagePullPolicy":"IfNotPresent","name":"productpage","ports":[{"containerPort":9080}],"securityContext":{"runAsUser":1000},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"serviceAccountName":"bookinfo-productpage","volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: productpage
          image: swr.cn-north-4.myhuaweicloud.com/hfbbg4/examples-bookinfo-productpage-v1:1.17.0
          ports:
            - containerPort: 9080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 10m
              memory: 24Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: bookinfo-productpage
      serviceAccount: bookinfo-productpage
      securityContext: {}
      schedulerName: default-scheduler
      tolerations: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
